name: Data Refresh

on:
    schedule:
        - cron: "0 */12 * * *"
jobs:
    refresh-data:
        runs-on: ubuntu-latest
        container:
            image: python:3.12
        steps:
            - name: checkout_repo
              uses: actions/checkout@v3
              with:
                ref: "main"
            - name: data refresh
              run: bash ./backend/data_refresh.sh
              shell: bash 
              env:
                CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                USER_EMAIL: ${{ secrets.USER_EMAIL }}
                USER_NAME: ${{ secrets.USER_NAME }}
