name: Hello World

on:
    schedule:
        - cron: "0 */1 * * *"
jobs:
    hello-world:
        runs-on: ubuntu-latest
        container:
            image: python:3.12
        steps:
            - name: print-hello-world
              run: echo "Hello World"
